config/routes.rb
Rails.application.routes.draw do
  get 'elements/show'

  root 'front_page#index'
  resources :requests
  devise_for :users
  
  
  resources :elements do 
    resources :estimations, only: [:destroy, :create]
  end
  
  
  get 'category/index'

  get 'category/show/:id', to: 'category#show'
  
  get 'regist/loginpage'
  #get 'front_page/index'
  get '/login', to: 'regist#loginpage'
  get '/category', to: 'category#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/detail.rb
class Detail < ApplicationRecord
    mount_uploader :img, PictureUploader
    validates_uniqueness_of :name
    belongs_to :subject
    has_many :elements
end

app/models/element.rb
class Element < ApplicationRecord
    before_save :set_average_to_0
    mount_uploader :img, PictureUploader
    validates_uniqueness_of :name
    
    belongs_to :subject
    belongs_to :detail
    has_many :estimations
    
    def set_average_to_0
       self.average = 0 if self.average.nil?
    end
end

app/models/estimation.rb
class Estimation < ApplicationRecord
    validates_uniqueness_of :user_id, :scope => :element_id
    belongs_to :user
    belongs_to :element
end

app/models/request.rb
class Request < ApplicationRecord
    
    belongs_to :user
end

app/models/subject.rb
class Subject < ApplicationRecord
    validates_uniqueness_of :name
    has_many :details
    has_many :elements
end

app/models/user.rb
class User < ApplicationRecord
  has_many :elements
  has_many :estimations
  has_many :requests
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def get_id
    self.email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :db_set
  
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
  
  private
  def db_set
    @subjects = Subject.all
    @details = Detail.all
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    Element.all.each do |e|
      e.average = e.estimations.average(:saticification).to_f
      e.save!
    end
    
    if params[:s_id].nil? && params[:d_id].nil?
      @elements = Element.all
    elsif params[:s_id].nil?
      @elements = Element.where(detail_id: params[:d_id])
    else
      @elements = Element.where(subject_id: params[:s_id])
    end
    
    # Element.joins(:detail).where()
    # Element.joins(:detail).joins(:subjects).where()
  end

  def show
    @element = Element.find(params[:id])
    @estimation = Estimation.new
    @estimations = @element.estimations
  end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  def show
    #@element = Element.find[params :id]
  end
end

app/controllers/estimations_controller.rb
class EstimationsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  def create
    estimation = Estimation.new
    estimation.element_id = params[:element_id]
    estimation.user = current_user
    estimation.comment = params[:estimation][:comment]
    estimation.saticification = params[:estimation][:saticification]
    
    estimation.save
    redirect_back(fallback_location: root_path)
  end

  
  
  def destroy
    estimation = Estimation.find(params[:id])
    estimation.destroy
    
    redirect_to category_index_path(params[:element_id])
  end
  
end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController
  def index
    if params[:s_id].nil? && params[:d_id].nil?
      @elements = Element.all
    elsif params[:s_id].nil?
      @elements = Element.where(detail_id: params[:d_id])
    else
      @elements = Element.where(subject_id: params[:s_id])
    end
  end
end

app/controllers/regist_controller.rb
class RegistController < ApplicationController
  def loginpage
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @requests = Request.all
  end

  def new
    @request = Request.new
  end
  
  def create
    @request = Request.new(params.require(:request).permit(:title, :content, :user_id))
    
    if @request.save
      flash[:success] = 'Request가 작성되었습니다!'
      redirect_to request_url(@request.id)
    else
      render 'new'
    end
  end

  def show
    @request = Request.find params[:id]
  end

  def edit
    @request = Request.find params[:id]
  end
  
  def update
    @request = Request.find params[:id]
    if @request.update(params.require(:request).permit(:title, :content, :user_id))
      redirect_to request_url(@request)
    else
      redirect_to edit_request_url(@request)
    end
  end
  
  def destroy
    @request = Request.find params[:id]
    @request.destroy
    redirect_to requests_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def asset_present?(name)
    # Rails 4.1 had Rails.application.assets filled out in all environments.
    # Rails 4.2 has it filled only when config.assets.compile == true which is only
    # in development by default.
    if Rails.application.assets.present?
      Rails.application.assets.find_asset(name)
    else
      Rails.application.assets_manifest.files.values.map { |v| v['logical_path'] }.include?(name)
    end
  end
end

app/helpers/category_helper.rb
module CategoryHelper
  
  
end

app/helpers/estimations_helper.rb
module EstimationsHelper
end

app/helpers/front_page_helper.rb
module FrontPageHelper
end

app/helpers/regist_helper.rb
module RegistHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/category/index.html.erb
<!--<%= @elements.each do |e| %>-->
<!--	<img src="<%=e.img%>" alt=""/>-->
<!--<% end %>-->
<!-- WRAPPER START -->
		<div class="wrapper bg-dark-white">
			<!-- Mobile-menu end -->
			<!-- HEADING-BANNER START -->
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<!--<img src="<%asset_path ='logo/Ranker.png' %>" alt="">-->
									<!--<a href="#"><img src="<%= asset_path 'banner/5.jpg' %>" alt="" /></a>-->
									<img src="<%= asset_path 'logo/Ranker.png' %>" alt=""/>
									<!--<h2></h2>-->
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="/">Home</a></li>
										<li>Product grid view</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- PRODUCT-AREA START -->
			<div class="product-area pt-80 pb-80 product-style-2">
				<div class="container">
					<div class="row">
						<div class="col-md-3 col-sm-12 col-xs-12">
							<!-- Widget-Search start -->
							<aside class="widget widget-search mb-30">
								<form action="#">
									<input type="text" placeholder="Search here..." />
									<button type="submit">
										<i class="zmdi zmdi-search"></i>
									</button>
								</form>
							</aside>
							<!-- Widget-search end -->
							
							<!-- Widget-Categories start -->
							<aside class="widget widget-categories  mb-30">
								<div class="widget-title">
									<a href="/category"><h4>Category</h4></a>
								</div>
								<div id="cat-treeview" class="widget-info product-cat boxscrol2">
									<ul>
										<% @subjects.each do |s| %>
											<li>
												<a href="/category/index?s_id=<%=s.id%>"><%= s.name %></a>
												<ul>
													<% @details.each do |d| %>
														<% if d.subject == s %>
															<li><a href="/category/index?d_id=<%=d.id%>"><%= d.name %></a></li>
														<% end %>
													<% end %>
												</ul>
											</li>
										<% end %>
									</ul>
								</div>
							</aside>
							
							<aside class="widget widget-banner hidden-sm">
								<div class="widget-info widget-banner-img">
									<a href="https://likelion.net/"><img src="<%= asset_path 'banner/add1.png' %>" alt="" /></a>
								</div>
							</aside>
							<!-- Widget-banner end -->
						</div>
						<div class="col-md-9 col-sm-12 col-xs-12">
							<div class="shop-content mt-tab-30 mt-xs-30">
								
								<!--<div class="product-option mb-30 clearfix">-->
									<!-- Nav tabs -->
								<!--	<ul class="shop-tab">-->
								<!--		<li class="active"><a href="#grid-view" data-toggle="tab"><i class="zmdi zmdi-view-module"></i></a></li>-->
								<!--		<li><a href="#list-view"  data-toggle="tab"><i class="zmdi zmdi-view-list"></i></a></li>-->
								<!--	</ul>-->
								<!--	<div class="showing text-right hidden-xs">-->
								<!--		<p class="mb-0">Showing 01-09 of 17 Results</p>-->
								<!--	</div>-->
								<!--</div>-->
								
								<!-- Tab panes -->
								<div class="tab-content">
									<div class="tab-pane active" id="grid-view">							
										<div class="row">
											<!-- Single-product start -->
											<% count = 0 %>
											<% @elements.order(:average).reverse_order.each do |e| %>
												<% count = count + 1 %>
												<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
													<div class="single-product">
														<div class="product-img">
															<span class="pro-label sale-label"><%= count %></span>
															<span class="pro-price-2"></span>
															<a href="/category/show/<%=e.id%>"><img src="<%= e.img.thumb.url %>" alt="" /></a>
														</div>
														<div class="product-info clearfix text-center">
															<div class="fix">
																<h4 class="post-title"><a href="#"><%= e.name %></a></h4>
															</div>
															<div class="fix">
																<span class="pro-rating">
																	<a href="#"><i class="zmdi zmdi-star"> <%= e.average %></i></a>
																</span>
															</div>
														</div>
													</div>
												</div>
											<% end %>
										</div>
									</div>
								</div>
								
								<!-- Pagination start -->
								<div class="shop-pagination  text-center">
									<div class="pagination">
										<ul>
											<li><a href="#"><i class="zmdi zmdi-long-arrow-left"></i></a></li>
											<li class="active"><a href="#">01</a></li>
											<li><a href="#">02</a></li>
											<li><a href="#">03</a></li>
											<li><a href="#">04</a></li>
											<li><a href="#">05</a></li>
											<li><a href="#"><i class="zmdi zmdi-long-arrow-right"></i></a></li>
										</ul>
									</div>
								</div>
								<!-- Pagination end -->
								
							</div>
							<!-- Shop-Content End -->
						</div>
					</div>
				</div>
			</div>
			<!-- PRODUCT-AREA END -->
		</div>
		<!-- WRAPPER END -->
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BranKing</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>Home one || Hurst</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%#= stylesheet_link_tag    params[:controller], media: 'all' %>

  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/regist/loginpage.html.erb
		<!-- WRAPPER START -->
		<div class="wrapper bg-dark-white">
			<!-- HEADING-BANNER START -->
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Registration</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="index.html">Home</a></li>
										<li>Registration</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			<div class="login-area  pt-80 pb-80">
				<div class="container">
					<form action="#">	
						<div class="row">
							
							<div class="col-md-6 col-sm-6 col-xs-12">
								<div class="user-login text-left">
									<h4 class="title-1 title-border text-uppercase mb-30">Registered users</h4>
									<p class="text-gray">If you have an account with us, Please login!</p>
									<input type="text" placeholder="Email here..." name="email">
									<input type="password" placeholder="Password">
									<p><a href="#" class="text-gray">Forget your password?</a></p>
									<button type="submit" data-text="login" class="button-one submit-button mt-15">login</button>
								</div>					
							</div>
							
							<div class="col-md-6 col-sm-6 col-xs-12">
								<div class="user-login text-left">
									<h4 class="title-1 title-border text-uppercase mb-30">NEW USER</h4>
									<p class="text-gray">If you have an account with us, Please login!</p>
									
									<input type="text" placeholder="Email address here..." name="email">
									<input type="password" placeholder="Password">
									<input type="password" placeholder="Confirm password">
									<p class="mb-0">
										<input type="checkbox" id="newsletter" name="newsletter" checked>
										<label for="newsletter"><span>Sign up for our newsletter!</span></label>
									</p>
									<button type="submit" data-text="regiter" class="button-one submit-button mt-15">regiter</button>
								</div>					
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<!-- WRAPPER END -->

app/views/requests/index.html.erb
<div class="wrapper bg-dark-white">
	<div class="heading-banner-area overlay-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="heading-banner">
						<div class="heading-banner-title">
							<!--<img src="<%asset_path ='logo/Ranker.png' %>" alt="">-->
							<!--<a href="#"><img src="<%= asset_path 'banner/5.jpg' %>" alt="" /></a>-->
							<img src="<%= asset_path 'logo/Ranker.png' %>" alt=""/>
							<!--<h2></h2>-->
						</div>
						<div class="breadcumbs pb-15">
							<ul>
								<li><a href="/">Home</a></li>
								<li>Request</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="product-area pt-80 pb-80 product-style-2">
		<div class="container">
			<div class="row">
				
				<div class="col-md-3 col-sm-12 col-xs-12">
	                <!-- Widget-Search start -->
					<aside class="widget widget-search mb-30">
						<form action="#">
							<input type="text" placeholder="Search here..." />
							<button type="submit">
								<i class="zmdi zmdi-search"></i>
							</button>
						</form>
					</aside>
					<!-- Widget-search end -->
					<!-- Widget-Categories start -->
					<aside class="widget widget-categories  mb-30">
						<div class="widget-title">
							<a href="/requests"><h4>Request</h4></a>
						</div>
					</aside>
					
					<aside class="widget widget-banner hidden-sm">
						<div class="widget-info widget-banner-img">
							<a href="http://www.multicampus.co.kr"><img src="<%= asset_path 'banner/add1.png' %>" alt="" /></a>
						</div>
					</aside>
        </div>
        
        
        <div class="col-md-9 col-sm-12 col-xs-12">
					<!-- tootle-Content End -->
	
							
              <div class="elements-accordions pt-80 pb-80">
                <div class="tab-content ">
                  <div class="tab-pane active" id="elements-preview-1">
              			<div class="row">
                    	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                      	<%= link_to 'New request', new_request_path, class:"button-one submit-button mt-15" %>
                      </div>
                    </div>
                    
                    <div class="row">
                    	<% count = Request.count + 1 %>
                    	<div class="col-4">순번</div>
                    	<div class="col-4">제목</div> 
                    	<div class="col-4">아이디</div><br>
                    	
                    	<% @requests.reverse_each do |req| %>
                      	<div class="col-4">
                      		<%= count = count - 1 %>
                    		</div>
                    		<div class="col-4">
                      		<%= link_to req.title, request_path(req) %>
                    		</div>
                    		<div class="col-4">
                    			<%= req.user.get_id %>
                    		</div>
                    	<% end %>
                  	</div>
                       
                  </div>
              	</div>
          		</div>
	      
      	</div>
	        
	        
	    </div>
		</div>
	</div>
	
	
</div>

app/views/requests/show.html.erb
<div class="wrapper bg-dark-white">
	<div class="heading-banner-area overlay-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="heading-banner">
						<div class="heading-banner-title">
							<!--<img src="<%asset_path ='logo/Ranker.png' %>" alt="">-->
							<!--<a href="#"><img src="<%= asset_path 'banner/5.jpg' %>" alt="" /></a>-->
							<img src="<%= asset_path 'logo/Ranker.png' %>" alt=""/>
							<!--<h2></h2>-->
						</div>
						<div class="breadcumbs pb-15">
							<ul>
								<li><a href="/">Home</a></li>
								<li>Request</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="product-area pt-80 pb-80 product-style-2">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-12 col-xs-12">
	                <!-- Widget-Search start <--></-->  
					<aside class="widget widget-search mb-30">
						<form action="#">
							<input type="text" placeholder="Search here..." />
							<button type="submit">
								<i class="zmdi zmdi-search"></i>
							</button>
						</form>
					</aside>
					<!-- Widget-search end -->
					
					<!-- Widget-Categories start -->
					<aside class="widget widget-categories  mb-30">
						<div class="widget-title">
							<a href="/requests"><h4>Request</h4></a>
						</div>
					</aside>
					
					<aside class="widget widget-banner hidden-sm">
						<div class="widget-info widget-banner-img">
							<a href="http://www.multicampus.co.kr"><img src="<%= asset_path 'banner/add1.png' %>" alt="" /></a>
						</div>
					</aside>
        </div>
        
	      <div class="col-md-9 col-sm-12 col-xs-12">
					<div class="shop-content mt-tab-30 mt-xs-30">
						<div class="product-option mb-30 clearfix">
              <div class="elements-accordions pt-80 pb-80">
                <div class="tab-content">
                  <div class="tab-pane active" id="elements-preview-1">
                  	<h1><%= @request.title %></h1>
                    <p>
                      <%= @request.content.html_safe %>
                    </p>
                    <div>
                    <%= link_to 'list', requests_path %>
                    |
                    <%= link_to 'edit', edit_request_path %>
                    |
                    <%= link_to 'delete', request_path(@request), method: :delete %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  	</div>
	</div>
</div>

app/views/shared/_header.html.erb
		<!-- WRAPPER START -->
		<div class="wrapper">
			<!-- Mobile-header-top Start -->
			<div class="mobile-header-top hidden-lg hidden-md hidden-sm">
				<div class="container">
					<div class="row">
						<div class="col-xs-12">
						</div>
					</div>
				</div>
			</div>
			<!-- Mobile-header-top End -->
			<!-- HEADER-AREA START -->
			<header id="sticky-menu" class="header">
				<div class="header-area">
					<div class="container-fluid">
						<div class="row">
							<div class="col-sm-4 col-sm-offset-4 col-xs-7">
								<div  align="center" class="logo text-center">
									<a href="/"><img src="<%= asset_path 'logo/logo.png' %>" alt="" /></a>
								</div>
							</div>
							<div class="col-sm-4 col-xs-5">
								<div class="table">
									<div style ="font-size:1.4em" align="center" class="table-cell">
										<ul>
											<!--<li><a href="/users/login" >Login<i class="zmdi zmdi-lock"></i></a></li>-->
											<% if user_signed_in? %>
												<li><%= link_to "LogOut ", destroy_user_session_path, method: :delete %><i class="zmdi zmdi-lock-open"></i></li>
											<% else %>
												<li><a href="/users/sign_in" > Login <i class="zmdi zmdi-lock"></i></a></li>
											<% end %>
											<li><a class="search-open" href="#">  Search <i class="zmdi zmdi-search"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- MAIN-MENU START -->
				<div class="menu-toggle hamburger hamburger--emphatic hidden-xs">
					<div class="hamburger-box">
						<div class="hamburger-inner"></div>
					</div>
				</div>
				<div class="main-menu  hidden-xs">
					<nav>
						<ul>
							<li><a href="/">Home</a></li>
                            <li><a href="/category">Category</a>
                                <div class="sub-menu menu-scroll">
                                    <ul>
                                        <!--<li class="menu-title">List</li>-->
                                        <div id="cat-treeview" class="widget-info product-cat boxscrol2">
                                        	<% @subjects.each do |s| %>
												<li>
													<a href='/category/index?s_id=<%=s.id%>'><%= s.name %></a>
													<ul>
														<% @details.each do |d| %>
															<% if d.subject == s %>
																<li><a href="/category/index?d_id=<%=d.id%>'"><%= d.name %></a></li>
															<% end %>
														<% end %>
													</ul>
												</li>
											<% end %>
                                        </div>
                                    </ul>
                                </div>
                            </li>
                            <li><%= link_to 'request', requests_path %></li>
                            <!--<li><a href="#">request</a></li>-->
							<!--<li><a href="shop-sidebar.html">accesories</a></li>-->
							<!--<li><a href="shop-list.html">lookbook</a></li>-->
							<!--<li><a href="blog.html">blog</a></li>-->
							<!--<li><a href="#">pages</a>-->
							<!--	<div class="sub-menu menu-scroll">-->
							<!--		<ul>-->
							<!--			<li class="menu-title">Page's</li>-->
							<!--			<li><a href="shop.html">Shop</a></li>-->
							<!--			<li><a href="shop-sidebar.html">Shop Sidebar</a></li>-->
							<!--			<li><a href="shop-grid-right-sidebar.html">Shop Right Sidebar</a></li>-->
							<!--			<li><a href="shop-list.html">Shop List</a></li>-->
							<!--			<li><a href="shop-list-right-sidebar.html">Shop List right sidebar</a></li>-->
							<!--			<li><a href="single-product.html">Single Product</a></li>-->
							<!--			<li><a href="single-product-sidebar.html">Single Product Sidebar</a></li>-->
							<!--			<li><a href="cart.html">Shopping Cart</a></li>-->
							<!--			<li><a href="wishlist.html">Wishlist</a></li>-->
							<!--			<li><a href="checkout.html">Checkout</a></li>-->
							<!--			<li><a href="order.html">Order</a></li>-->
							<!--			<li><a href="/users/sign_in">login / Registration</a></li>-->
							<!--			<li><a href="my-account.html">My Account</a></li>-->
							<!--			<li><a href="404.html">404</a></li>-->
							<!--			<li><a href="blog.html">Blog</a></li>-->
							<!--			<li><a href="single-blog.html">Single Blog</a></li>-->
							<!--			<li><a href="single-blog-sidebar.html">Single Blog Sidebar</a></li>-->
							<!--			<li><a href="about.html">About Us</a></li>-->
							<!--			<li><a href="contact.html">Contact</a></li>-->
							<!--		</ul>-->
							<!--	</div>-->
							<!--</li>-->
							<li><a href="about.html">about us</a></li>
							<li><a href="contact.html">contact</a></li>
						</ul>
					</nav>
				</div>
				<!-- MAIN-MENU END -->
			</header>
			<!-- HEADER-AREA END -->
			<!-- Mobile-menu start -->
			<div class="mobile-menu-area">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-12 hidden-lg hidden-md hidden-sm">
							<div class="mobile-menu">
								<nav id="dropdown">
									<ul>
										<li><a href="/">Home</a></li>
			                            <li><a href="/category">Category</a>
			                                <div class="sub-menu menu-scroll">
			                                    <ul>
			                                        <!--<li class="menu-title">List</li>-->
			                                        <div id="cat-treeview" class="widget-info product-cat boxscrol2">
			                                        	<% @subjects.each do |s| %>
																									<li>
																										<a href="/category/index?s_id=<%=s.id%>"><%= s.name %></a>
																										<ul>
																											<% @details.each do |d| %>
																												<% if d.subject == s %>
																													<li><a href="/category/index?d_id=<%=d.id%>"><%= d.name %></a></li>
																												<% end %>
																											<% end %>
																										</ul>
																									</li>
																								<% end %>
			                                        </div>
			                                    </ul>
			                                </div>
			                            </li>
			                            <li><a href="/requests">request</a></li>
										<!--<li><a href="shop-sidebar.html">accesories</a></li>-->
										<!--<li><a href="shop-list.html">lookbook</a></li>-->
										<!--<li><a href="blog.html">blog</a></li>-->
										<!--<li><a href="#">pages</a>-->
										<!--	<div class="sub-menu menu-scroll">-->
										<!--		<ul>-->
										<!--			<li class="menu-title">Page's</li>-->
										<!--			<li><a href="shop.html">Shop</a></li>-->
										<!--			<li><a href="shop-sidebar.html">Shop Sidebar</a></li>-->
										<!--			<li><a href="shop-grid-right-sidebar.html">Shop Right Sidebar</a></li>-->
										<!--			<li><a href="shop-list.html">Shop List</a></li>-->
										<!--			<li><a href="shop-list-right-sidebar.html">Shop List right sidebar</a></li>-->
										<!--			<li><a href="single-product.html">Single Product</a></li>-->
										<!--			<li><a href="single-product-sidebar.html">Single Product Sidebar</a></li>-->
										<!--			<li><a href="cart.html">Shopping Cart</a></li>-->
										<!--			<li><a href="wishlist.html">Wishlist</a></li>-->
										<!--			<li><a href="checkout.html">Checkout</a></li>-->
										<!--			<li><a href="order.html">Order</a></li>-->
										<!--			<li><a href="/users/sign_in">login / Registration</a></li>-->
										<!--			<li><a href="my-account.html">My Account</a></li>-->
										<!--			<li><a href="404.html">404</a></li>-->
										<!--			<li><a href="blog.html">Blog</a></li>-->
										<!--			<li><a href="single-blog.html">Single Blog</a></li>-->
										<!--			<li><a href="single-blog-sidebar.html">Single Blog Sidebar</a></li>-->
										<!--			<li><a href="about.html">About Us</a></li>-->
										<!--			<li><a href="contact.html">Contact</a></li>-->
										<!--		</ul>-->
										<!--	</div>-->
										<!--</li>-->
										<li><a href="about.html">about us</a></li>
										<li><a href="contact.html">contact</a></li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Mobile-menu end -->